// flow-typed signature: 395d5ad9d76e22628db5bd9ee0d71717
// flow-typed version: <<STUB>>/haz-touch_v^1.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'haz-touch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'haz-touch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'haz-touch/index' {
  declare module.exports: $Exports<'haz-touch'>;
}
declare module 'haz-touch/index.js' {
  declare module.exports: $Exports<'haz-touch'>;
}
