// flow-typed signature: 8d2ed97384b0a7cacdcf002a19b864bf
// flow-typed version: <<STUB>>/physicsjs_v^0.7.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'physicsjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'physicsjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'physicsjs/dist/behaviors/attractor' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/behaviors/body-collision-detection' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/behaviors/body-impulse-response' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/behaviors/constant-acceleration' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/behaviors/edge-collision-detection' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/behaviors/interactive' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/behaviors/newtonian' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/behaviors/sweep-prune' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/behaviors/verlet-constraints' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/bodies/circle' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/bodies/compound' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/bodies/convex-polygon' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/bodies/rectangle' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/geometries/circle' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/geometries/compound' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/geometries/convex-polygon' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/geometries/rectangle' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/integrators/improved-euler' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/integrators/velocity-verlet-alt' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/integrators/velocity-verlet' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/physicsjs-full' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/physicsjs-full.min' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/physicsjs' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/physicsjs.min' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/renderers/canvas' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/renderers/debug' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/renderers/dom' {
  declare module.exports: any;
}

declare module 'physicsjs/dist/renderers/pixi-renderer' {
  declare module.exports: any;
}

declare module 'physicsjs/docs/js/page' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/codemirror/codemirror' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/codemirror/mode/css' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/codemirror/mode/htmlmixed' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/codemirror/mode/javascript' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/codemirror/mode/xml' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/editor' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/esprima' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/rawdeflate' {
  declare module.exports: any;
}

declare module 'physicsjs/editor/js/rawinflate' {
  declare module.exports: any;
}

declare module 'physicsjs/examples/physicsjs-full' {
  declare module.exports: any;
}

declare module 'physicsjs/gruntfile' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/almond' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/dat.gui' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/gendoc' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/lodash' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/lodash.min' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/pixi' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/raf' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/require' {
  declare module.exports: any;
}

declare module 'physicsjs/lib/stats' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/attractor' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/body-collision-detection' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/body-impulse-response' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/constant-acceleration' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/edge-collision-detection' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/interactive' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/newtonian' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/sweep-prune' {
  declare module.exports: any;
}

declare module 'physicsjs/src/behaviors/verlet-constraints' {
  declare module.exports: any;
}

declare module 'physicsjs/src/bodies/circle' {
  declare module.exports: any;
}

declare module 'physicsjs/src/bodies/compound' {
  declare module.exports: any;
}

declare module 'physicsjs/src/bodies/convex-polygon' {
  declare module.exports: any;
}

declare module 'physicsjs/src/bodies/point' {
  declare module.exports: any;
}

declare module 'physicsjs/src/bodies/rectangle' {
  declare module.exports: any;
}

declare module 'physicsjs/src/core/behavior' {
  declare module.exports: any;
}

declare module 'physicsjs/src/core/body' {
  declare module.exports: any;
}

declare module 'physicsjs/src/core/geometry-helpers' {
  declare module.exports: any;
}

declare module 'physicsjs/src/core/geometry' {
  declare module.exports: any;
}

declare module 'physicsjs/src/core/integrator' {
  declare module.exports: any;
}

declare module 'physicsjs/src/core/query' {
  declare module.exports: any;
}

declare module 'physicsjs/src/core/renderer' {
  declare module.exports: any;
}

declare module 'physicsjs/src/core/world' {
  declare module.exports: any;
}

declare module 'physicsjs/src/geometries/circle' {
  declare module.exports: any;
}

declare module 'physicsjs/src/geometries/compound' {
  declare module.exports: any;
}

declare module 'physicsjs/src/geometries/convex-polygon' {
  declare module.exports: any;
}

declare module 'physicsjs/src/geometries/point' {
  declare module.exports: any;
}

declare module 'physicsjs/src/geometries/rectangle' {
  declare module.exports: any;
}

declare module 'physicsjs/src/integrators/improved-euler' {
  declare module.exports: any;
}

declare module 'physicsjs/src/integrators/velocity-verlet-alt' {
  declare module.exports: any;
}

declare module 'physicsjs/src/integrators/velocity-verlet' {
  declare module.exports: any;
}

declare module 'physicsjs/src/integrators/verlet' {
  declare module.exports: any;
}

declare module 'physicsjs/src/intro' {
  declare module.exports: any;
}

declare module 'physicsjs/src/math/aabb' {
  declare module.exports: any;
}

declare module 'physicsjs/src/math/gjk' {
  declare module.exports: any;
}

declare module 'physicsjs/src/math/statistics' {
  declare module.exports: any;
}

declare module 'physicsjs/src/math/transform' {
  declare module.exports: any;
}

declare module 'physicsjs/src/math/vector' {
  declare module.exports: any;
}

declare module 'physicsjs/src/outro' {
  declare module.exports: any;
}

declare module 'physicsjs/src/renderers/canvas' {
  declare module.exports: any;
}

declare module 'physicsjs/src/renderers/debug' {
  declare module.exports: any;
}

declare module 'physicsjs/src/renderers/dom' {
  declare module.exports: any;
}

declare module 'physicsjs/src/renderers/pixi-renderer' {
  declare module.exports: any;
}

declare module 'physicsjs/src/util/decorator' {
  declare module.exports: any;
}

declare module 'physicsjs/src/util/helpers' {
  declare module.exports: any;
}

declare module 'physicsjs/src/util/noconflict' {
  declare module.exports: any;
}

declare module 'physicsjs/src/util/pubsub' {
  declare module.exports: any;
}

declare module 'physicsjs/src/util/scratchpad' {
  declare module.exports: any;
}

declare module 'physicsjs/src/util/ticker' {
  declare module.exports: any;
}

declare module 'physicsjs/test/node/basic.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/r.js.spec.helper' {
  declare module.exports: any;
}

declare module 'physicsjs/test/requirejs.build.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/requirejs.spec.helper' {
  declare module.exports: any;
}

declare module 'physicsjs/test/requirejs.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/aabb.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/collision-detection.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/convex-polygon.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/decorator.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/geometry.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/noconflict.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/pubsub.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/query.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/transform.spec' {
  declare module.exports: any;
}

declare module 'physicsjs/test/spec/world-add-remove.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'physicsjs/dist/behaviors/attractor.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/attractor'>;
}
declare module 'physicsjs/dist/behaviors/body-collision-detection.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/body-collision-detection'>;
}
declare module 'physicsjs/dist/behaviors/body-impulse-response.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/body-impulse-response'>;
}
declare module 'physicsjs/dist/behaviors/constant-acceleration.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/constant-acceleration'>;
}
declare module 'physicsjs/dist/behaviors/edge-collision-detection.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/edge-collision-detection'>;
}
declare module 'physicsjs/dist/behaviors/interactive.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/interactive'>;
}
declare module 'physicsjs/dist/behaviors/newtonian.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/newtonian'>;
}
declare module 'physicsjs/dist/behaviors/sweep-prune.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/sweep-prune'>;
}
declare module 'physicsjs/dist/behaviors/verlet-constraints.js' {
  declare module.exports: $Exports<'physicsjs/dist/behaviors/verlet-constraints'>;
}
declare module 'physicsjs/dist/bodies/circle.js' {
  declare module.exports: $Exports<'physicsjs/dist/bodies/circle'>;
}
declare module 'physicsjs/dist/bodies/compound.js' {
  declare module.exports: $Exports<'physicsjs/dist/bodies/compound'>;
}
declare module 'physicsjs/dist/bodies/convex-polygon.js' {
  declare module.exports: $Exports<'physicsjs/dist/bodies/convex-polygon'>;
}
declare module 'physicsjs/dist/bodies/rectangle.js' {
  declare module.exports: $Exports<'physicsjs/dist/bodies/rectangle'>;
}
declare module 'physicsjs/dist/geometries/circle.js' {
  declare module.exports: $Exports<'physicsjs/dist/geometries/circle'>;
}
declare module 'physicsjs/dist/geometries/compound.js' {
  declare module.exports: $Exports<'physicsjs/dist/geometries/compound'>;
}
declare module 'physicsjs/dist/geometries/convex-polygon.js' {
  declare module.exports: $Exports<'physicsjs/dist/geometries/convex-polygon'>;
}
declare module 'physicsjs/dist/geometries/rectangle.js' {
  declare module.exports: $Exports<'physicsjs/dist/geometries/rectangle'>;
}
declare module 'physicsjs/dist/integrators/improved-euler.js' {
  declare module.exports: $Exports<'physicsjs/dist/integrators/improved-euler'>;
}
declare module 'physicsjs/dist/integrators/velocity-verlet-alt.js' {
  declare module.exports: $Exports<'physicsjs/dist/integrators/velocity-verlet-alt'>;
}
declare module 'physicsjs/dist/integrators/velocity-verlet.js' {
  declare module.exports: $Exports<'physicsjs/dist/integrators/velocity-verlet'>;
}
declare module 'physicsjs/dist/physicsjs-full.js' {
  declare module.exports: $Exports<'physicsjs/dist/physicsjs-full'>;
}
declare module 'physicsjs/dist/physicsjs-full.min.js' {
  declare module.exports: $Exports<'physicsjs/dist/physicsjs-full.min'>;
}
declare module 'physicsjs/dist/physicsjs.js' {
  declare module.exports: $Exports<'physicsjs/dist/physicsjs'>;
}
declare module 'physicsjs/dist/physicsjs.min.js' {
  declare module.exports: $Exports<'physicsjs/dist/physicsjs.min'>;
}
declare module 'physicsjs/dist/renderers/canvas.js' {
  declare module.exports: $Exports<'physicsjs/dist/renderers/canvas'>;
}
declare module 'physicsjs/dist/renderers/debug.js' {
  declare module.exports: $Exports<'physicsjs/dist/renderers/debug'>;
}
declare module 'physicsjs/dist/renderers/dom.js' {
  declare module.exports: $Exports<'physicsjs/dist/renderers/dom'>;
}
declare module 'physicsjs/dist/renderers/pixi-renderer.js' {
  declare module.exports: $Exports<'physicsjs/dist/renderers/pixi-renderer'>;
}
declare module 'physicsjs/docs/js/page.js' {
  declare module.exports: $Exports<'physicsjs/docs/js/page'>;
}
declare module 'physicsjs/editor/js/codemirror/codemirror.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/codemirror/codemirror'>;
}
declare module 'physicsjs/editor/js/codemirror/mode/css.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/codemirror/mode/css'>;
}
declare module 'physicsjs/editor/js/codemirror/mode/htmlmixed.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/codemirror/mode/htmlmixed'>;
}
declare module 'physicsjs/editor/js/codemirror/mode/javascript.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/codemirror/mode/javascript'>;
}
declare module 'physicsjs/editor/js/codemirror/mode/xml.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/codemirror/mode/xml'>;
}
declare module 'physicsjs/editor/js/editor.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/editor'>;
}
declare module 'physicsjs/editor/js/esprima.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/esprima'>;
}
declare module 'physicsjs/editor/js/rawdeflate.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/rawdeflate'>;
}
declare module 'physicsjs/editor/js/rawinflate.js' {
  declare module.exports: $Exports<'physicsjs/editor/js/rawinflate'>;
}
declare module 'physicsjs/examples/physicsjs-full.js' {
  declare module.exports: $Exports<'physicsjs/examples/physicsjs-full'>;
}
declare module 'physicsjs/gruntfile.js' {
  declare module.exports: $Exports<'physicsjs/gruntfile'>;
}
declare module 'physicsjs/lib/almond.js' {
  declare module.exports: $Exports<'physicsjs/lib/almond'>;
}
declare module 'physicsjs/lib/dat.gui.js' {
  declare module.exports: $Exports<'physicsjs/lib/dat.gui'>;
}
declare module 'physicsjs/lib/gendoc.js' {
  declare module.exports: $Exports<'physicsjs/lib/gendoc'>;
}
declare module 'physicsjs/lib/lodash.js' {
  declare module.exports: $Exports<'physicsjs/lib/lodash'>;
}
declare module 'physicsjs/lib/lodash.min.js' {
  declare module.exports: $Exports<'physicsjs/lib/lodash.min'>;
}
declare module 'physicsjs/lib/pixi.js' {
  declare module.exports: $Exports<'physicsjs/lib/pixi'>;
}
declare module 'physicsjs/lib/raf.js' {
  declare module.exports: $Exports<'physicsjs/lib/raf'>;
}
declare module 'physicsjs/lib/require.js' {
  declare module.exports: $Exports<'physicsjs/lib/require'>;
}
declare module 'physicsjs/lib/stats.js' {
  declare module.exports: $Exports<'physicsjs/lib/stats'>;
}
declare module 'physicsjs/src/behaviors/attractor.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/attractor'>;
}
declare module 'physicsjs/src/behaviors/body-collision-detection.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/body-collision-detection'>;
}
declare module 'physicsjs/src/behaviors/body-impulse-response.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/body-impulse-response'>;
}
declare module 'physicsjs/src/behaviors/constant-acceleration.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/constant-acceleration'>;
}
declare module 'physicsjs/src/behaviors/edge-collision-detection.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/edge-collision-detection'>;
}
declare module 'physicsjs/src/behaviors/interactive.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/interactive'>;
}
declare module 'physicsjs/src/behaviors/newtonian.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/newtonian'>;
}
declare module 'physicsjs/src/behaviors/sweep-prune.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/sweep-prune'>;
}
declare module 'physicsjs/src/behaviors/verlet-constraints.js' {
  declare module.exports: $Exports<'physicsjs/src/behaviors/verlet-constraints'>;
}
declare module 'physicsjs/src/bodies/circle.js' {
  declare module.exports: $Exports<'physicsjs/src/bodies/circle'>;
}
declare module 'physicsjs/src/bodies/compound.js' {
  declare module.exports: $Exports<'physicsjs/src/bodies/compound'>;
}
declare module 'physicsjs/src/bodies/convex-polygon.js' {
  declare module.exports: $Exports<'physicsjs/src/bodies/convex-polygon'>;
}
declare module 'physicsjs/src/bodies/point.js' {
  declare module.exports: $Exports<'physicsjs/src/bodies/point'>;
}
declare module 'physicsjs/src/bodies/rectangle.js' {
  declare module.exports: $Exports<'physicsjs/src/bodies/rectangle'>;
}
declare module 'physicsjs/src/core/behavior.js' {
  declare module.exports: $Exports<'physicsjs/src/core/behavior'>;
}
declare module 'physicsjs/src/core/body.js' {
  declare module.exports: $Exports<'physicsjs/src/core/body'>;
}
declare module 'physicsjs/src/core/geometry-helpers.js' {
  declare module.exports: $Exports<'physicsjs/src/core/geometry-helpers'>;
}
declare module 'physicsjs/src/core/geometry.js' {
  declare module.exports: $Exports<'physicsjs/src/core/geometry'>;
}
declare module 'physicsjs/src/core/integrator.js' {
  declare module.exports: $Exports<'physicsjs/src/core/integrator'>;
}
declare module 'physicsjs/src/core/query.js' {
  declare module.exports: $Exports<'physicsjs/src/core/query'>;
}
declare module 'physicsjs/src/core/renderer.js' {
  declare module.exports: $Exports<'physicsjs/src/core/renderer'>;
}
declare module 'physicsjs/src/core/world.js' {
  declare module.exports: $Exports<'physicsjs/src/core/world'>;
}
declare module 'physicsjs/src/geometries/circle.js' {
  declare module.exports: $Exports<'physicsjs/src/geometries/circle'>;
}
declare module 'physicsjs/src/geometries/compound.js' {
  declare module.exports: $Exports<'physicsjs/src/geometries/compound'>;
}
declare module 'physicsjs/src/geometries/convex-polygon.js' {
  declare module.exports: $Exports<'physicsjs/src/geometries/convex-polygon'>;
}
declare module 'physicsjs/src/geometries/point.js' {
  declare module.exports: $Exports<'physicsjs/src/geometries/point'>;
}
declare module 'physicsjs/src/geometries/rectangle.js' {
  declare module.exports: $Exports<'physicsjs/src/geometries/rectangle'>;
}
declare module 'physicsjs/src/integrators/improved-euler.js' {
  declare module.exports: $Exports<'physicsjs/src/integrators/improved-euler'>;
}
declare module 'physicsjs/src/integrators/velocity-verlet-alt.js' {
  declare module.exports: $Exports<'physicsjs/src/integrators/velocity-verlet-alt'>;
}
declare module 'physicsjs/src/integrators/velocity-verlet.js' {
  declare module.exports: $Exports<'physicsjs/src/integrators/velocity-verlet'>;
}
declare module 'physicsjs/src/integrators/verlet.js' {
  declare module.exports: $Exports<'physicsjs/src/integrators/verlet'>;
}
declare module 'physicsjs/src/intro.js' {
  declare module.exports: $Exports<'physicsjs/src/intro'>;
}
declare module 'physicsjs/src/math/aabb.js' {
  declare module.exports: $Exports<'physicsjs/src/math/aabb'>;
}
declare module 'physicsjs/src/math/gjk.js' {
  declare module.exports: $Exports<'physicsjs/src/math/gjk'>;
}
declare module 'physicsjs/src/math/statistics.js' {
  declare module.exports: $Exports<'physicsjs/src/math/statistics'>;
}
declare module 'physicsjs/src/math/transform.js' {
  declare module.exports: $Exports<'physicsjs/src/math/transform'>;
}
declare module 'physicsjs/src/math/vector.js' {
  declare module.exports: $Exports<'physicsjs/src/math/vector'>;
}
declare module 'physicsjs/src/outro.js' {
  declare module.exports: $Exports<'physicsjs/src/outro'>;
}
declare module 'physicsjs/src/renderers/canvas.js' {
  declare module.exports: $Exports<'physicsjs/src/renderers/canvas'>;
}
declare module 'physicsjs/src/renderers/debug.js' {
  declare module.exports: $Exports<'physicsjs/src/renderers/debug'>;
}
declare module 'physicsjs/src/renderers/dom.js' {
  declare module.exports: $Exports<'physicsjs/src/renderers/dom'>;
}
declare module 'physicsjs/src/renderers/pixi-renderer.js' {
  declare module.exports: $Exports<'physicsjs/src/renderers/pixi-renderer'>;
}
declare module 'physicsjs/src/util/decorator.js' {
  declare module.exports: $Exports<'physicsjs/src/util/decorator'>;
}
declare module 'physicsjs/src/util/helpers.js' {
  declare module.exports: $Exports<'physicsjs/src/util/helpers'>;
}
declare module 'physicsjs/src/util/noconflict.js' {
  declare module.exports: $Exports<'physicsjs/src/util/noconflict'>;
}
declare module 'physicsjs/src/util/pubsub.js' {
  declare module.exports: $Exports<'physicsjs/src/util/pubsub'>;
}
declare module 'physicsjs/src/util/scratchpad.js' {
  declare module.exports: $Exports<'physicsjs/src/util/scratchpad'>;
}
declare module 'physicsjs/src/util/ticker.js' {
  declare module.exports: $Exports<'physicsjs/src/util/ticker'>;
}
declare module 'physicsjs/test/node/basic.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/node/basic.spec'>;
}
declare module 'physicsjs/test/r.js.spec.helper.js' {
  declare module.exports: $Exports<'physicsjs/test/r.js.spec.helper'>;
}
declare module 'physicsjs/test/requirejs.build.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/requirejs.build.spec'>;
}
declare module 'physicsjs/test/requirejs.spec.helper.js' {
  declare module.exports: $Exports<'physicsjs/test/requirejs.spec.helper'>;
}
declare module 'physicsjs/test/requirejs.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/requirejs.spec'>;
}
declare module 'physicsjs/test/spec/aabb.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/aabb.spec'>;
}
declare module 'physicsjs/test/spec/collision-detection.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/collision-detection.spec'>;
}
declare module 'physicsjs/test/spec/convex-polygon.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/convex-polygon.spec'>;
}
declare module 'physicsjs/test/spec/decorator.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/decorator.spec'>;
}
declare module 'physicsjs/test/spec/geometry.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/geometry.spec'>;
}
declare module 'physicsjs/test/spec/noconflict.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/noconflict.spec'>;
}
declare module 'physicsjs/test/spec/pubsub.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/pubsub.spec'>;
}
declare module 'physicsjs/test/spec/query.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/query.spec'>;
}
declare module 'physicsjs/test/spec/transform.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/transform.spec'>;
}
declare module 'physicsjs/test/spec/world-add-remove.spec.js' {
  declare module.exports: $Exports<'physicsjs/test/spec/world-add-remove.spec'>;
}
